# Generated by Django 3.1.2 on 2020-10-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='body',
            field=models.TextField(default=1, help_text='Write your chapter here', max_length=20480),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.series'),
        ),
    ]
