# Generated by Django 3.1.2 on 2020-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Draft'), ('a', 'Alpha'), ('b', 'Beta'), ('f', 'Final')], default='d', help_text='Chapter Status', max_length=1),
        ),
    ]
