# Generated by Django 3.1.2 on 2020-10-26 19:42

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
