# Generated by Django 3.1.2 on 2021-01-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201026_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Fiction or Non Fiction', max_length=50)),
            ],
        ),
    ]
