# Generated by Django 3.1.2 on 2021-01-11 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_narrativeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='narrative',
            field=models.ForeignKey(help_text='Select if this is a work of fiction or non-fiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.narrativeform'),
        ),
    ]
