# Generated by Django 3.1.2 on 2021-01-12 00:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
