# Generated by Django 3.1.2 on 2021-01-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_series_book_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='book_number',
        ),
        migrations.AddField(
            model_name='book',
            name='series_number',
            field=models.IntegerField(default=1),
        ),
    ]
