# Generated by Django 3.1.2 on 2021-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210116_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
